#!/bin/bash

cd /home/ubuntu
sudo apt-get update 
sudo apt install -y \
    python3 \
    unzip \
    python3-pip 
sudo apt-get install -y ffmpeg libsm6 libxext6

git clone https://github.com/brenogibson/cv-heatmap-demos.git
cd cv-heatmap-demos/src/ec2/
pip3 install -r requirements.txt --break-system-packages

curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install

python3 app.py